### PR TITLE
disable telegraf ; solve grafana deps problem in Terraform

### PR DESCRIPTION
**Pull request by nonsense**

### CODE REVIEW

**Comment by nonsense** [comment]
We no longer have to run `make` twice - running it once starts influxdb, grafana, waits for 10sec for grafana to come up, and then adds data sources and dashboards.

I removed `telegraf` as we are not going to use `statsd` for now.

cc @holisticode @gbalint

**Comment by holisticode** [comment]
Great stuff. Can you confirm it actually starts `geth` as well? When I used this the first time last week, I suddenly had 15GB of net traffic, and it seemd to be due to `geth` running with this cluster. Maybe we can have `geth` optional?

**Comment by janos** [comment]
Great, thanks Anton!

**Comment by nonsense** [comment]
@holisticode no, it doesn't start `geth`. The user/developer is free to decide how to run `geth` - on the host, or in a VM, or in a container. This is only metrics setup.

**Comment by holisticode** [comment]
hmmm `main.tf` actually contains 
```
41 # Geth container runs one contianer with geth process.
 42 resource "docker_container" "geth" {
```

**Comment by janos** [comment]
@holisticode you are probably referring to swarm-test-cluster/main.tf, not swarm-metrics/main.tf.

**Pull request merged**
